DROP TABLE IF EXISTS `company`;
CREATE TABLE `company` (
  `ID_COMPANY` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` varchar(200) NOT NULL,
  `COMPANY_ADDRESS` varchar(200),
  `COMPANY_CONTACT` varchar(20),
   PRIMARY KEY (`ID_COMPANY`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `ID_PRODUCT` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `PCOMPANY_NAME` varchar(512),
  `PRODUCT_NAME` varchar(200),
   PRIMARY KEY (`ID_PRODUCT`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `dealers`;
CREATE TABLE `dealers` (
  `ID_USER` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(200),
  `USER_ROAD` varchar(200),
   PRIMARY KEY (`ID_USER`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `stock`;
CREATE TABLE `stock` (
  `ID_INVENTORY` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ID_PRODUCT` varchar(200),
  `PRODUCT_NAME` varchar(200),
  `SRATE` varchar(200),
  `SQUANTITY` varchar(200),
  `DATE_INVENTORY` date,
  `SAMOUNT` varchar(200),
   PRIMARY KEY (`ID_INVENTORY`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `ID_ORDER` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `OPRODUCT_NAME` varchar(512),
  `ID_USER` varchar(512),
  `ORATE` varchar(512),
  `OQUANTITY` varchar(512),
  `DATE_ORDER` date,
  `OAMOUNT` varchar(512),
  `ORDER_NUMBER` varchar(512),
   PRIMARY KEY (`ID_ORDER`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `returns`;
CREATE TABLE `returns` (
  `ID_RETURN` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `RPRODUCT_NAME` varchar(512),
  `ID_USER` varchar(512),
  `RRATE` varchar(512),
  `RQUANTITY` varchar(512),
  `DATE_RETURN` date,
  `RAMOUNT` varchar(512),
  `RORDER_NUMBER` varchar(512),
   PRIMARY KEY (`ID_RETURN`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `damage`;
CREATE TABLE `damage` (
  `ID_DAMAGE` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `DPRODUCT_NAME` varchar(512),
  `ID_USER` varchar(512),
  `DRATE` varchar(512),
  `DQUANTITY` varchar(512),
  `DATE_DAMAGE` date,
  `DAMOUNT` varchar(512),
  `DORDER_NUMBER` varchar(512),
   PRIMARY KEY (`ID_DAMAGE`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;



